name: Outdated Issue & Pull Requests - Pipeline
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    name: Automatic closing of outdated issues & pull requests
    runs-on: ubuntu-latest
    steps:
    - uses: DeMoorJasper/stale@v2.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days'
        exempt-labels: 'bug, bot,documentation'
        days-before-stale: 30
        days-before-close: 5
